repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [ "--quiet", '--experimental-string-processing' ]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: double-quote-string-fixer

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8_deps
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-print
          - flake8-mutable
          - flake8-simplify
          - flake8-pytest-style
          - flake8-printf-formatting

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: *flake8_deps

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.5.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", '--py38-plus', '--py39-plus', '--keep-runtime-typing' ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        files: 'bender/.*|tests/.*'
        additional_dependencies:
          - types-orjson
          - types-paramiko
          - types-redis
          - types-pytz
